//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSWA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharValue : IEquatable<CharValue>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CharValue()
        {
            this.ItemCharacteristics = new HashSet<ItemCharacteristic>();
        }
    
        public System.Guid id { get; set; }
        public Nullable<int> intVal { get; set; }
        public Nullable<double> floatVal { get; set; }
        public string strVal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemCharacteristic> ItemCharacteristics { get; set; }

        public bool Equals(CharValue other)
        {
            if (this.id == other.id)
            {
                return true;
            }
            else {
                return false;
            }
        }
    }
}
