//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSWA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> CommentTypeId { get; set; }
        public string Comment1 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual CommentType CommentType { get; set; }
        public virtual Item Item { get; set; }
        public virtual user user { get; set; }
    }
}
