//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSWA.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class purposePrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purposePrice()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid purposeId { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public System.Guid curencyID { get; set; }
    
        public virtual Curency Curency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Purpose Purpose { get; set; }
    }
}
